NyxLex - Verify adding  more products to comparison from comparison page
Lv-630-TAQC-Java-project/RozetkaAutomation pull request #115
Opened 2021-12-07 12:02 UTC by NyxLex

2021-12-07 12:17 UTC, anastasia8755 approved these changes

2021-12-07 15:25 UTC, Percifalll approved these changes

2021-12-08 06:47 UTC, toleksyn requested changes

2021-12-08 06:47 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/test/ComparisonTest.java
> +                .addProductCountToComparison(3);
does this add product number 3 or 3 same products to comparison?

2021-12-08 07:25 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/test/ComparisonTest.java
> +                .addProductCountToComparison(3);
addProductsToComparison(int productsToAdd)

2021-12-09 06:38 UTC, merged