VladDmutriv - create new framework for RozetkaAutomation
Lv-630-TAQC-Java-project/RozetkaAutomation pull request #52
Opened 2021-11-09 21:35 UTC by vladdmytriv

another type of framework for Rozetka 

I saw that we will have a lot of same PO's and methods in it on Rozetka branch. Lots of element open the same page so I try to identify needed pages and write methods that will open the same page from different elements.

2021-11-09 21:41 UTC, vladdmytriv commented on src/main/java/com/ss/ita/google/ui/pages/HomePage.java
> -import static com.codeborne.selenide.Selectors.byName;
just fix conflicts after merging

2021-11-10 06:21 UTC, toleksyn requested changes

2021-11-10 06:21 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/Modals/BasketModal.java
> +    public String getPriceWithCurrency() {
what if more than one product?

2021-11-10 06:21 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/Modals/BasketModal.java
> +    public int getPrice() {
same thing

2021-11-10 06:21 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/ProductsEnum/GeneralProductCategories.java
> +public enum GeneralProductCategories {
singular

2021-11-10 06:21 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/ProductsEnum/ProductCategoriesAndSubCategories.java
> +public enum ProductCategoriesAndSubCategories {
same

2021-11-10 06:21 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/pages/HomePage.java
> +    public List<SelenideElement> getHomePageProductList(){
no selenide elems sticking out of PO

2021-11-10 06:21 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/verifyOpeningProductPage.java
> +                .openProductPage(1);
this not complete, do not create not finished PRs

2021-11-10 06:21 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/verifyOpeningProductPage.java
> +public class verifyOpeningProductPage extends TestRunnerForRozetka {
???

2021-11-11 06:24 UTC, toleksyn requested changes

2021-11-11 06:24 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/pages/HomePage.java
> +    private static final String GENERAL_PRODUCT_CATEGORY_TEMPLATE = "//div[contains(@class,'menu-wrapper_state_static')]/descendant::a[contains(@href,'%s')]";
if used once, inline

2021-11-11 06:24 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/pages/ProductCategoryPage.java
> +    private static final String PRODUCT_CATEGORY_OR_SUBCATEGORY_TEMPLATE = "//a[contains(@href,'%s')]";
same

2021-11-11 06:24 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/pages/ProductCategoryPage.java
> +    private static final String PRODUCT_CATEGORY_OR_SUBCATEGORY_TEMPLATE = "//a[contains(@href,'%s')]";
same for all

2021-11-11 06:28 UTC, vladdmytriv commented on src/main/java/com/ss/ita/rozetka/ui/Modals/HamburgerModal.java
> +        $x("//nav[@class='drawer ng-star-inserted']").shouldNotBe(Condition.visible);
Taras why U push your commits in my PR?

Like I know we use testng assertion, don't we?

2021-11-11 07:24 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/Modals/CatalogModal.java
> +public class CatalogModal extends Header {
abstrtact HeaderPage {
      protected Header  header = new Header();
}

catalogModal.header.search()

2021-11-11 07:46 UTC, merged