Refactored method. Added methods for products - edit count, remove.
Lv-630-TAQC-Java-project/RozetkaAutomation pull request #53
Opened 2021-11-10 12:00 UTC by Percifalll

2021-11-11 07:11 UTC, toleksyn requested changes

2021-11-11 07:11 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/Modals/BasketModal.java
> +        countField.sendKeys(count + "");
String.valueOf()

2021-11-15 06:30 UTC, toleksyn requested changes

2021-11-15 06:30 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/Modals/BasketModal.java
> +                "//input[contains(@class, 'cart-counter__input')]";
String.format(PRODUCT_XPATH_PATTERN_FOR_NAME + "//input[contains(@class, 'cart-counter__input')]", productName)
same for others

2021-11-16 06:25 UTC, toleksyn requested changes

2021-11-16 06:25 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/Modals/BasketModal.java
> +    public void close() {
shout return a PO

2021-11-17 06:16 UTC, toleksyn requested changes

2021-11-17 06:16 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/Modals/BasketModal.java
> +    public BasketModal(T rootPage) {
where is T used?

2021-11-17 06:16 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/Modals/BasketModal.java
> +    @Step("BasketModal: get product names ")
remove space

2021-11-17 07:21 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/Modals/BasketModal.java
> +    public BasketModal(T rootPage) {
rename

2021-11-17 07:22 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/Modals/BasketModal.java
> +    public List<String> getProductNames() {
rename

2021-11-17 07:23 UTC, toleksyn requested changes

2021-11-17 07:23 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/Modals/BasketModal.java
> +    private void waitForTotalPriceToUpdate(int totalPriceBefore) {
step

2021-11-17 12:34 UTC, vladdmytriv commented on src/main/java/com/ss/ita/rozetka/ui/Modals/BasketModal.java
> +    @Step("BasketModal: order products you chose")
selected

2021-11-17 13:10 UTC, Percifalll commented on src/main/java/com/ss/ita/rozetka/ui/Modals/BasketModal.java
> +    @Step("BasketModal: order products you chose")
you was not assigned to review

2021-11-18 06:23 UTC, toleksyn requested changes

2021-11-18 06:23 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/Modals/BasketModal.java
> +    private static final String PRODUCT_XPATH_PATTERN_FOR_NAME = "//single-modal-window//li[contains(., '%s')]";
if %s in name - template

2021-11-18 08:19 UTC, NazarYakh approved these changes

2021-11-18 09:04 UTC, NazarYakh approved these changes

2021-11-18 16:18 UTC, dzhyv approved these changes

2021-11-19 06:10 UTC, toleksyn requested changes

2021-11-19 06:10 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/Modals/BasketModal.java
> +    @Step("BasketModal: check if basket is empty")
there's no check here

2021-11-19 07:56 UTC, vladdmytriv approved these changes

2021-11-19 07:57 UTC, NazarYakh approved these changes

2021-11-19 09:00 UTC, merged