dzhyv/Click on rozetka logo test + getUrl method
Lv-630-TAQC-Java-project/RozetkaAutomation pull request #62
Opened 2021-11-10 21:56 UTC by dzhyv

2021-11-11 06:29 UTC, toleksyn requested changes

2021-11-11 06:29 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/rozetka/clickRozetkaLogoTest.java
> +public class clickRozetkaLogoTest {
java code convention

2021-11-11 06:29 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/rozetka/clickRozetkaLogoTest.java
> +                .openProductCategoryPage(PRODUCTS_FOR_HOUSE.getName())
re-do openProductCategoryPage() to work with enum directly

2021-11-11 06:29 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/rozetka/clickRozetkaLogoTest.java
> +    public void verifyClickRozetkaLogo(){
where does it click on logo in test?

2021-11-15 06:32 UTC, toleksyn requested changes

2021-11-15 06:32 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/pages/HeaderPage.java
> +    public Header header = new Header();
no public fields in PO

2021-11-15 06:32 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/ui/NavigatingToHomePageTest.java
> +                .openProductTypePage(KITCHEN_APPLIANCES_CATEGORY)
how do we know this page opened at all?

2021-11-16 06:25 UTC, toleksyn requested changes

2021-11-16 06:25 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/ui/NavigatingToHomePageTest.java
> +                .getHeader()
three times getHeader()

2021-11-17 06:30 UTC, toleksyn requested changes

2021-11-17 06:30 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/ui/NavigatingToHomePageTest.java
> +public class NavigatingToHomePageTest extends TestRunner {
NavigationTest

2021-11-17 06:30 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/ui/NavigatingToHomePageTest.java
> +                .isEqualTo("https://bt.rozetka.com.ua/tehnika-dlya-kuhni/c435974/");
checking that page opened only by URL is not fool proof and never enough

2021-11-18 06:24 UTC, toleksyn requested changes

2021-11-18 06:24 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/pages/HomePage.java
> +    @Step("HomePage: verify that home page slider is visible")
this is not verification

2021-11-19 06:09 UTC, toleksyn requested changes

2021-11-19 06:09 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/pages/HomePage.java
> +    public boolean isSliderVisible() {
isOpened(), then it will read as homePage.isOpened()

2021-11-19 07:36 UTC, toleksyn requested changes

2021-11-19 07:36 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/test/NavigationTest.java
> +        ProductCategoryPage page = new HomePage()
page -> productCategoryPage

2021-11-19 08:03 UTC, anastasia8755 approved these changes

2021-11-19 08:25 UTC, NazarYakh approved these changes

2021-11-19 09:02 UTC, merged