NazarYakh_change_language_test
Lv-630-TAQC-Java-project/RozetkaAutomation pull request #65
Opened 2021-11-11 11:09 UTC by NazarYakh

2021-11-15 06:36 UTC, toleksyn requested changes

2021-11-15 06:36 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/ui/ChangeLanguageTest.java
> +        Assert.assertEquals(new HomePage()
this is bad design, you re-open page each time and create 4(!) homePage obejcts

2021-11-16 06:22 UTC, toleksyn requested changes

2021-11-16 06:22 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/ui/ChangeLanguageTest.java
> +        homePage.getHeader().changeLanguage("RU");
why call header twice?

2021-11-17 06:28 UTC, toleksyn requested changes

2021-11-17 06:28 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/elements/Header.java
>      public Header changeLanguage(String language) {
step?

2021-11-17 06:28 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/ui/ChangeLanguageTest.java
> +        Assert.assertEquals(homePage
assertj ?

2021-11-17 06:28 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/ui/ChangeLanguageTest.java
> +                .getGreetingsText(), "Ласкаво просимо!", "Language wasn't changed");
should

2021-11-18 06:26 UTC, toleksyn requested changes

2021-11-18 06:26 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/ui/ChangeLanguageTest.java
> +                .getGreetingsText()).as("Language should be changed").contains("Добро пожаловать!");
format things porperly

2021-11-19 06:07 UTC, toleksyn requested changes

2021-11-19 06:07 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/ui/LocalizationTests.java
> +public class LocalizationTests extends TestRunner {
Test, singular

2021-11-19 07:59 UTC, NyxLex approved these changes

2021-11-19 09:39 UTC, merged