Xiaomi search test
Lv-630-TAQC-Java-project/RozetkaAutomation pull request #66
Opened 2021-11-11 13:12 UTC by NazarYakh

2021-11-15 06:37 UTC, toleksyn requested changes

2021-11-15 06:37 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/pages/ProductTypePage.java
> +        return $$("span.goods-tile__title").get(productNumber).getText();
use direct locators, not $$x().get(number)

2021-11-15 06:37 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/ui/XiaomiSearchTest.java
> +        Assert.assertTrue(new ProductTypePage().getProductTitle(1).contains("Xiaomi"));
where's the PO chain?

2021-11-15 07:18 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/ui/XiaomiSearchTest.java
> +        Assert.assertTrue(new ProductTypePage().getProductTitle(1).contains("Xiaomi"));
remove duplication

2021-11-16 06:21 UTC, toleksyn requested changes

2021-11-16 06:21 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/pages/ProductTypePage.java
> +    public String getFirstProductTitle() {
NO hard coding

2021-11-16 06:21 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/ui/XiaomiSearchTest.java
> +    String searchProduct = "Xiaomi";
???

2021-11-16 07:12 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/ui/XiaomiSearchTest.java
> +    String searchProduct = "Xiaomi";
inline

2021-11-17 06:27 UTC, toleksyn requested changes

2021-11-17 06:27 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/ui/XiaomiSearchTest.java
> +public class XiaomiSearchTest extends TestRunner {
rename

2021-11-17 06:27 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/ui/XiaomiSearchTest.java
> +        Assert.assertTrue(productTypePage.getProductTitle(1).contains(searchProduct));
assertj

2021-11-17 06:27 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/pages/ProductTypePage.java
> +    public String getProductTitle(int productNumber) {
step?

2021-11-18 06:27 UTC, toleksyn requested changes

2021-11-18 06:27 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/ui/SearchFunctionalityTests.java
> +                .as("Product should have Xiaomi in title").contains(searchProduct);
format things properly

2021-11-19 06:07 UTC, toleksyn requested changes

2021-11-19 06:07 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/ui/SearchFunctionalityTests.java
> +public class SearchFunctionalityTests extends TestRunner {
Test, singular

2021-11-19 07:58 UTC, dzhyv approved these changes

2021-11-19 09:44 UTC, merged