Verify that products in notebook category are presented
Lv-630-TAQC-Java-project/RozetkaAutomation pull request #67
Opened 2021-11-12 09:50 UTC by anastasia8755

2021-11-15 06:39 UTC, toleksyn requested changes

2021-11-15 06:39 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/pages/ProductTypePage.java
> +    public boolean isThereMoreThanNProductsOnPagePresented(int n) {
what's n?
re-do into getProducts() and do your comparison in the test

2021-11-15 07:20 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/ProductsEnum/ProductCategoryAndSubCategory.java
> +    NOTEBOOKS("notebooks/c80004/"),
investigate

2021-11-15 07:22 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/pages/ProductTypePage.java
> +    public boolean isThereMoreThanNProductsOnPagePresented(int n) {
getProductsCount()

2021-11-16 06:20 UTC, toleksyn requested changes

2021-11-16 06:20 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/pages/ProductTypePage.java
> +        return $$(".catalog-grid__cell").size();
this won't wait

2021-11-16 07:10 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/pages/ProductTypePage.java
> +        return $$(".catalog-grid__cell").size();
$$x().shouldHaveSizeAtLeast(1).size()

2021-11-17 06:26 UTC, toleksyn requested changes

2021-11-17 06:26 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/pages/ProductTypePage.java
> +                        .sizeGreaterThan(1))
format

2021-11-17 06:26 UTC, toleksyn commented on src/test/com/ss/ita/rozetka/ProductsInCategoryArePresentedTest.java
> +                .getProductsCount())
format

2021-11-18 06:27 UTC, toleksyn requested changes

2021-11-18 06:27 UTC, toleksyn commented on src/test/com/ss/ita/rozetka/ProductsInCategoryArePresentedTest.java
> +public class ProductsInCategoryArePresentedTest extends TestRunner {
fix class name

2021-11-19 06:06 UTC, toleksyn requested changes

2021-11-19 06:06 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/pages/ProductTypePage.java
> +        return $$(".catalog-grid__cell").shouldHave(CollectionCondition.sizeGreaterThan(1)).size();
format

2021-11-19 08:02 UTC, dzhyv approved these changes

2021-11-19 08:10 UTC, NyxLex approved these changes

2021-11-19 08:21 UTC, NazarYakh approved these changes

2021-11-19 09:44 UTC, merged