VladDmytriv - add test to cover OrderingPage functionality and POs methods for this test
Lv-630-TAQC-Java-project/RozetkaAutomation pull request #79
Opened 2021-11-17 15:09 UTC by vladdmytriv

2021-11-18 06:36 UTC, toleksyn requested changes

2021-11-18 06:36 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/pages/OrderingPage.java
> +    public OrderingPage sidebarShouldBeVisible() {
get status, assert in test

2021-11-19 06:03 UTC, toleksyn requested changes

2021-11-19 06:03 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/pages/ProductPage.java
> +        actions().moveToElement($x("//button[contains(@class,'buy-button button button_')]")).click().perform();
format

2021-11-19 07:26 UTC, toleksyn requested changes

2021-11-19 07:26 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/pages/OrderingPage.java
> +    public OrderingPage orderingPageShouldBeOpened() {
boolean isOrderingPageOpened()

2021-11-19 07:34 UTC, toleksyn requested changes

2021-11-19 07:34 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/pageobject/pages/OrderingPage.java
> +    public OrderingPage orderingPageShouldBeOpened() {
re-do method to boolean isOpened() and assert in test 
fix step

2021-11-19 08:04 UTC, Percifalll approved these changes

2021-11-19 09:41 UTC, toleksyn requested changes

2021-11-19 09:41 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/test/OrderingProductsTest.java
> +                .as("OpderingPage should be opened")
fix

2021-11-19 09:41 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/pageobject/pages/OrderingPage.java
> +    @Step("OrderingPage: get ordering page status, assert in test")
remove assert in test

2021-11-19 10:26 UTC, merged