NyxLex - Verify add button functionality
Lv-630-TAQC-Java-project/RozetkaAutomation pull request #83
Opened 2021-11-18 11:44 UTC by NyxLex

# Conflicts:
#	src/main/java/com/ss/ita/rozetka/ui/ProductsEnum/ProductCategoryAndSubCategory.java
#	src/main/java/com/ss/ita/rozetka/ui/pages/HeaderPage.java

2021-11-18 15:14 UTC, Percifalll approved these changes

2021-11-19 06:01 UTC, toleksyn requested changes

2021-11-19 06:01 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/BasketTest.java
> +    public void verifyAddButtonFunctionality() {
add product

2021-11-19 06:01 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/BasketTest.java
> +                .openProductPage(0)
either openProduct(0) or openProductPageForProduct(0)

2021-11-19 07:14 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/BasketTest.java
> +                .openProductPage(0)
re-do method to start with 1

2021-11-19 07:37 UTC, toleksyn requested changes

2021-11-19 07:37 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/ui/pages/HeaderPage.java
> +}
this shouldn't be here, sync your branch with main properly

2021-11-19 08:06 UTC, Percifalll approved these changes

2021-11-19 08:10 UTC, anastasia8755 approved these changes

2021-11-19 09:40 UTC, toleksyn requested changes

2021-11-19 09:40 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/pageobject/modals/BasketModal.java
> +    public BasketModal increaseAmountOfProduct(int numberOfProducts, int sequenceNumberOfProduct) {
productNumber, increaseNumber

2021-11-19 09:40 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/pageobject/modals/BasketModal.java
> +    public BasketModal decreaseAmountOfProduct(int numberOfProducts, int sequenceNumberOfProduct) {
productNumber, decreaseNumber

2021-11-19 12:53 UTC, merged