NyxLex - Login modal
Lv-630-TAQC-Java-project/RozetkaAutomation pull request #93
Opened 2021-11-25 15:37 UTC by NyxLex

2021-11-29 17:12 UTC, Percifalll approved these changes

2021-12-01 07:59 UTC, toleksyn requested changes

2021-12-01 07:59 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/pageobject/modals/LoginModal.java
> +    public Header closeLoginModal() {
close()

2021-12-01 07:59 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/pageobject/modals/LoginModal.java
> +        SelenideElement input = $x("//input[@type='email']");
setLoginEmail()
inputField?

2021-12-01 07:59 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/pageobject/modals/LoginModal.java
> +        SelenideElement input = $("#auth_pass");
inputField?

2021-12-01 07:59 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/test/LoginModalTest.java
> +                .isEqualTo(true);
isTrue()
same for all

2021-12-01 07:59 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/test/LoginModalTest.java
> +        loginModal.setLogin("test@gmail.com").setPassword("1111");
format

2021-12-01 10:12 UTC, NazarYakh approved these changes

2021-12-02 06:43 UTC, merged