NyxLex -Comparison test extension
Lv-630-TAQC-Java-project/RozetkaAutomation pull request #94
Opened 2021-11-29 14:51 UTC by NyxLex

2021-12-01 08:01 UTC, toleksyn requested changes

2021-12-01 08:01 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/pageobject/pages/ComparisonPage.java
> +    public int sizeOfProductComparisonList() {
rename

2021-12-01 08:01 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/pageobject/pages/ProductTypePage.java
> +    private List<SelenideElement> getProductComparisonIcons(int productCount) {
this is used once, why separate method?

2021-12-01 08:01 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/test/ComparisonTest.java
> +        int comparisonProductListSize = new Header()
DO NOT create raw page objects in test
get it from existing PO

2021-12-01 10:12 UTC, NazarYakh approved these changes

2021-12-02 06:44 UTC, toleksyn requested changes

2021-12-02 06:44 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/pageobject/pages/ProductTypePage.java
> +        }
why don't just click the elem directly?

2021-12-02 07:09 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/pageobject/pages/ProductTypePage.java
> +    public ProductTypePage addNumberOfProductsToComparison(int productCount) {
fix step and name

2021-12-03 06:38 UTC, merged