created buyProductTest
Lv-630-TAQC-Java-project/RozetkaAutomation pull request #95
Opened 2021-11-29 15:55 UTC by NazarYakh

2021-11-29 18:01 UTC, NyxLex approved these changes

2021-12-01 08:03 UTC, toleksyn requested changes

2021-12-01 08:03 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/pageobject/pages/OrderingPage.java
> +        return $x("//p[contains(text(),\"Введіть своє ім'я кирилицею\")]").isDisplayed();
do not use Cyrillic in locators
same for all

2021-12-01 08:03 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/pageobject/pages/OrderingPage.java
> +    public void confirmTheOrder() {
confirmOrdering

2021-12-01 08:03 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/pageobject/pages/OrderingPage.java
> +    public void confirmTheOrder() {
PO method should return this or new PO

2021-12-01 08:03 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/test/BuyProductTest.java
> +                .isEqualTo(urlAfterConfirmingOrder);
different or same?

2021-12-02 06:45 UTC, merged