(LVTAQC630-30) Verify that recently opened products is displayed on Rozetka home page from latest opened to earliest opened product
Lv-630-TAQC-Java-project/RozetkaAutomation pull request #96
Opened 2021-11-29 19:10 UTC by dzhyv

2021-11-29 19:21 UTC, Taras-Kr approved these changes

2021-11-29 19:37 UTC, anastasia8755 approved these changes

2021-11-30 08:52 UTC, NyxLex approved these changes

2021-12-01 08:05 UTC, toleksyn requested changes

2021-12-01 08:05 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/pageobject/pages/HomePage.java
> +        return names;
use $x().texts() instead

2021-12-01 08:05 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/test/RecentlyViewedProductsTest.java
> +                .getHeader()
re-use line 48

2021-12-01 08:05 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/test/RecentlyViewedProductsTest.java
> +                .getHeader()
same for all

2021-12-01 18:49 UTC, Percifalll commented on src/main/java/com/ss/ita/rozetka/pageobject/pages/HomePage.java
> +    public List<String> getRecentlyViewedProductsNames(/*int itemNumber*/){
no commented code in PR

2021-12-01 18:51 UTC, Percifalll commented on src/main/java/com/ss/ita/rozetka/pageobject/pages/HomePage.java
> +        return  $$x("//section[@class = 'main-goods ng-star-inserted'][1]//ul/li//a[@class = 'tile__title']").texts();
move xpath string to local variable

2021-12-01 18:53 UTC, Percifalll requested changes
.

2021-12-02 07:08 UTC, toleksyn requested changes

2021-12-02 07:08 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/pageobject/pages/HomePage.java
> +        return  $$x(recentlyViewedProductsXpath).texts();
$$x() has no waits

2021-12-02 07:08 UTC, toleksyn commented on src/test/java/com/ss/ita/rozetka/test/RecentlyViewedProductsTest.java
> +                .isEqualTo(firstOpenedProductName);
think about soft assert

2021-12-02 07:40 UTC, Percifalll approved these changes

2021-12-03 06:39 UTC, toleksyn requested changes

2021-12-03 06:39 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/pageobject/pages/HomePage.java
> +        return  $$x("//section[@class = 'main-goods ng-star-inserted'][1]//ul/li//a[@class = 'tile__title']").shouldBe(sizeNotEqual(0)).texts();
format

2021-12-06 06:26 UTC, toleksyn requested changes

2021-12-06 06:26 UTC, toleksyn commented on src/main/java/com/ss/ita/rozetka/pageobject/pages/HomePage.java
> +        return $$x("//section[@class = 'main-goods ng-star-inserted'][1]//ul/li//a[@class = 'tile__title']").shouldBe(sizeNotEqual(0)).texts();
format

2021-12-06 07:33 UTC, merged